schema_version = "1.0.0"

id = "telltalegames_d3dmesh_importer"
version = "0.0.1"
name = "TelltaleGames D3DMesh Importer"
tagline = "WIP"
maintainer = "Weasel On a Stick"
type = "add-on"


website = "https://github.com/WeaselOnaStick/TelltaleGames_D3DMesh_Importer"

tags = ["Import-Export",]

blender_version_min = "4.2.0"

license = ["SPDX:GPL-2.0-or-later",]

[permissions]
files = "Import D3DMesh/SKL files"